openapi: 3.0.0
info:
  title: Estates API
  version: 1.0.0
  description: API для работы с недвижимостью

servers:
  - url: /api
    description: Local Estate Server

components:
  schemas:
    Estate:
      type: object
      required:
        - id
        - address
        - city
        - currency
        - price
        - type
      properties:
        id:
          type: integer
          format: int64
        address:
          type: string
        city:
          type: string
        currency:
          type: string
        price:
          type: integer
          format: int64
        type:
          type: string
    FilterParams:
      type: object
      required:
        - city
        - type
        - search
      properties:
        city:
          type: string
        type:
          type: string
        search:
          type: string

paths:
  /estates:
    get:
      summary: Получить список объектов недвижимости
      description: Возвращает список объектов недвижимости с возможностью фильтрации
      parameters:
        - name: type
          in: query
          schema:
            type: string
          description: Тип недвижимости
          required: false
        - name: search
          in: query
          schema:
            type: string
          description: Поисковый запрос по адресу
          required: false
        - name: city
          in: query
          schema:
            type: string
          description: Город
          required: false
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Estate'
